#!/usr/bin/python3 -u
import os.path

KEY_FILE = "key"
KEY_LEN = 50000
FLAG_FILE = "flag"


def startup(key_location): # the key location always starts at 0 
	flag = open(FLAG_FILE).read()
	kf = open(KEY_FILE, "rb").read() # reading it in byte mode

	start = key_location	# start from 0
	stop = key_location + len(flag) # the stop becomes at the length of the flag

	key = kf[start:stop] # This variable get the length of the flag as the start from 0 and ends at the flag length 
	key_location = stop # the location is now assigned to the new value which is the length of the flag

	result = list(map(lambda p, k: "{:02x}".format(ord(p) ^ k), flag, key))

	#Explanation of the main core function
	'''The lambda here works as a loop to iterate the 'p' as a letter from the flag and 'k' as a byte from the key, and then
	apply the XOR on p which is converted into its ASCII integer value using k, and then formatted into 2 hexa places 
	(eg. 1 = 0x01). The map function stops the process once on of the iterables is exhausted.'''


	print("This is the encrypted flag!\n{}\n".format("".join(result)))

	return key_location		#Returns the key location which now became the length of the flag

def encrypt(key_location):
	ui = input("What data would you like to encrypt? ").rstrip()
	if len(ui) == 0 or len(ui) > KEY_LEN:	# input verification if nothing entered or input is greate than 50000
		return -1

	start = key_location	# Start from the flag length and not 0 as used below
	stop = key_location + len(ui) # a new length is generated by adding the input length of the user to the length of the flag

	kf = open(KEY_FILE, "rb").read()

	if stop >= KEY_LEN:		#Checking if the length is greater than 50000
		stop = stop % KEY_LEN	# if so the new value will be the modulus(reminder) of dividing the old stop value with 50000 
		key = kf[start:] + kf[:stop]	# the length of the key will be starting from the length of the flag and stop at the new location
	else:
		key = kf[start:stop]
	key_location = stop

	result = list(map(lambda p, k: "{:02x}".format(ord(p) ^ k), ui, key)) # same concept as the previous, and no going back just carrying on

	print("Here ya go!\n{}\n".format("".join(result)))

	return key_location


print("******************Welcome to our OTP implementation!******************")
c = startup(0)
while c >= 0:
	c = encrypt(c)
